name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit:
    runs-on: self-hosted
    container:
      image: node:alpine

    steps:
      - name: Install git
        run: apk add git

      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Lint commit
        env:
          EVENT_NAME: ${{ forgejo.event_name }}
          PR_TITLE: ${{ forgejo.event.pull_request.title }}
          COMMIT_MESSAGE: ${{ forgejo.event.head_commit.message }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            echo "$PR_TITLE" | commitlint
          else
            echo "$COMMIT_MESSAGE" | commitlint
          fi
