name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit:
    runs-on: self-hosted
    container:
      image: node:alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install Commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Lint commit
        run: |
          if [ "${{ forgejo.event_name }}" == "pull_request" ]; then
            echo "${{ forgejo.event.pull_request.title }}" | commitlint
          else
            echo "${{ forgejo.event.head_commit.message }}" | commitlint
          fi
