name: Cleanup PR Registry

on:
  pull_request:
    types: [closed]

jobs:
  delete-tag:
    runs-on: self-hosted
    container:
      image: alpine/curl:latest
    steps:
      - name: Delete PR Tag from Registry
        run: |
          # image tag name
          TAG_NAME="pr-${{ forgejo.event.pull_request.number }}"

          curl -f -s -X DELETE \
            -H "Authorization: token ${{ secrets.REGISTRY_PASS }}" \
            "https://${{ vars.REGISTRY }}/api/v1/packages/${{ forgejo.repository_owner }}/container/${{ forgejo.event.repository.name }}/$TAG_NAME"
