name: Docs Check

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".forgejo/workflows/swagger-check.yml"
  pull_request:
    paths:
      - "server/**"
      - ".forgejo/workflows/swagger-check.yml"

jobs:
  ci:
    name: Check Docs Sync
    runs-on: self-hosted

    container:
      image: codeberg.org/pranaovs/go-ci:latest@sha256:f4129fd085810baaf6966b2de56722852b758e85722e414e1ead564b700d5393

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Swagger docs check
        working-directory: server
        run: |
          swag init --quiet
          if [ -n "$(git status --porcelain docs/)" ]; then
            echo "Error: Swagger documentation is out of sync with code changes."
            echo "Please run 'swag init' in the server directory locally and commit the result."
            git diff docs/
            exit 1
          fi
