# build
FROM golang:1.26-alpine@sha256:f1ddd9fe14fffc091dd98cb4bfa999f32c5fc77d2f2305ea9f0e2595c5437c14 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 \
  go build -o qashare

# run
FROM gcr.io/distroless/base-debian12@sha256:58695f439f772a00009c8f6be4c183f824c1f556d74b313c30900f167e4772f8

WORKDIR /app

COPY --from=builder /build/qashare /app/qashare
COPY --from=builder /build/migrations /app/migrations

EXPOSE 5000

USER nonroot:nonroot

ENTRYPOINT ["/app/qashare"]
