# build
FROM golang:1.26-alpine@sha256:f85330846cde1e57ca9ec309382da3b8e6ae3ab943d2739500e08c86393a21b1 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 \
  go build -o qashare

# run
FROM gcr.io/distroless/static-debian12

WORKDIR /app

COPY --from=builder /build/qashare /app/qashare
COPY --from=builder /build/migrations /app/migrations

EXPOSE 5000

USER nonroot:nonroot

ENTRYPOINT ["/app/qashare"]
