#!/usr/bin/env sh

# Check if swag is installed
if ! command -v swag >/dev/null 2>&1; then
  echo "Error: 'swag' is not installed. Please install it to commit."
  exit 1
fi

STASH_NAME="pre-commit-swag-$(date +%s)"
STASH_CREATED=1
BACKEND_DIR="server/"

git stash push --keep-index -u -m "$STASH_NAME" >/dev/null 2>&1

# Check if a stash was actually created
if git stash list | grep -q "$STASH_NAME"; then
  STASH_CREATED=0
fi

# Function to restore state on exit
restore_state() {
  if [ "$STASH_CREATED" -eq 0 ]; then
    # Restore the unstaged changes
    git stash pop >/dev/null 2>&1
  fi
}

trap restore_state EXIT

echo "Generating swagger docs"

if ! swag i --dir "$BACKEND_DIR" --output "$BACKEND_DIR/docs"; then
  echo "Error: swag init failed."
  exit 1
fi

git add "$BACKEND_DIR/docs/"

exit 0
